### ISSUE TITLE
Shadowlands Pre-Patch Errors

### ISSUE THREAD

**Issue by Meebsy** [Ravendwyr/HandyNotes_AzerothsTopTunes#1]
`Message: ...nterface\AddOns\HandyNotes_AzerothsTopTunes\Core.lua:229: attempt to call upvalue 'GetQuestsCompleted' (a nil value)
Time: Wed Oct 14 09:49:32 2020
Count: 1
Stack: ...nterface\AddOns\HandyNotes_AzerothsTopTunes\Core.lua:229: attempt to call upvalue 'GetQuestsCompleted' (a nil value)`

**Comment by Ravendwyr** [comment]
Fixed in a5acaa5db6155add0a7becb0aae6aa65e9107e81

Thank you. :)
